name: Elixir CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: '1.14.2' # Define the elixir version [required]
        otp-version: '25.1.2' # Define the OTP version [required]
    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Install dependencies
      run: mix deps.get
    - name: Run Tests
      run: mix coveralls.json
      env:
        MIX_ENV: test
        AUTH_API_KEY: ${{ secrets.AUTH_API_KEY }}
        ENCRYPTION_KEYS: ${{ secrets.ENCRYPTION_KEYS }}
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1

  # Continuous Deployment to Fly.io
  # https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    needs: build
    # https://stackoverflow.com/questions/58139406/only-run-job-on-specific-branch-with-github-actions
    if: github.ref == 'refs/heads/main'
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions@1.1
        with:
          args: "deploy"
